[package]
name = "shuttle-bot-swbox-rust"
version = "0.2.0"
edition = "2021"
publish = false

[dependencies]
anyhow = "1.0.97"
poise = "0.6.1"
shuttle-runtime = "0.53.0"
shuttle-serenity = "0.53.0"
tokio = "1.44.1"
log = "0.4.26"
reqwest = { version = "0.12.15", features = ["json", "blocking"] }
serde = { version = "1.0.219", features = ["derive"] }
serde_json = "1.0.140"
lazy_static = "1.5.0"
chrono = "0.4.40"
image = "0.25.5"
futures = "0.3.31"
mongodb = "3.2.2"
