[package]
name = "shuttle-bot-swbox-rust"
version = "0.2.0"
edition = "2021"
publish = false

[dependencies]
anyhow = "1.0.98"
poise = "0.6.1"
shuttle-runtime = "0.53.0"
shuttle-serenity = "0.53.0"
tokio = "1.44.2"
log = "0.4.27"
reqwest = { version = "0.12.15", features = ["json", "blocking", "rustls-tls"] }
serde = { version = "1.0.219", features = ["derive"] }
serde_json = "1.0.140"
lazy_static = "1.5.0"
chrono = "0.4.40"
image = "0.25.6"
futures = "0.3.31"
mongodb = "3.2.3"
md5 = "0.7.0"
urlencoding = "2.1.3"
rand = "0.9.1"
imageproc = "0.25.0"
rusttype = "0.9"
ab_glyph = "0.2"